#include <vector>

#include "command_enums.h"

namespace {
std::vector<std::string> kCommandNames{
    "None",
    "Begin Command Buffer",
    "Begin Debug Utils Label EXT",
    "Begin Query",
    "Begin Renderpass",
    "Bind Descriptor Sets",
    "Bind Index Buffer",
    "Bind Pipeline",
    "Bind Vertex Buffers",
    "Blit Image",
    "Clear Attachments",
    "Clear Color Image",
    "Clear Depth Stencil Image",
    "Copy Buffer",
    "Copy Buffer to Image",
    "Copy Image",
    "Copy Image to Buffer",
    "Copy Query Pool Results",
    "Debug Marker Begin EXT",
    "Debug Marker End EXT",
    "Debug Marker Insert EXT",
    "Dispatch",
    "Dispatch Base",
    "Dispatch Base KHR",
    "Dispatch Indirect",
    "Draw",
    "Draw Indexed",
    "Draw Indexed Indirect",
    "Draw Indexed Indirect Count AMD",
    "Draw Indirect",
    "Draw Indirect Count AMD",
    "End Command Buffer",
    "End Debug Utils Label EXT",
    "End Query",
    "End Renderpass",
    "Execute Commands",
    "Fill Buffer",
    "Insert Debug Utils Label EXT",
    "Next Subpass",
    "Pipeline Barrier",
    "PROCESSCommand SNVX",
    "Push Constants",
    "Push Descriptor Set KHR",
    "Push Descriptor Set With Template KHR",
    "Reserve Space For Commands NVX",
    "Reset Command Buffer",
    "Reset Event",
    "Reset Query Pool",
    "Resolve Image",
    "Set Blend Constants",
    "Set Depth Bias",
    "Set Depth Bounds",
    "Set Device Mask",
    "Set Device Mask KHR",
    "Set Discard Rectangle EXT",
    "Set Event",
    "Set Line Width",
    "Set Sample Locations EXT",
    "Set Scissor",
    "Set Stencil Compare Mask",
    "Set Stencil Reference",
    "Set Stencil Write Mask",
    "Set Viewport",
    "Set Viewport W Scaling NV",
    "Update Buffer",
    "Wait Events",
    "Write Buffer Marker AMD",
    "Write Timestamp",
};
}

std::string cmdToString(CMD_TYPE cmd) { return kCommandNames[cmd]; }
